version: '3'

services:
  app:
    build: .
    container_name: app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/app
    depends_on:
      - db_app
    ports:
      - "9000:9000"
    environment:
      DJANGO_SETTINGS_MODULE: settings.settings.dev
      SWAGGER_BASE_URL=http://0:0:0:0:9000:
      POSTGRES_DB: settings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db_app
      POSTGRES_PORT: 5432
    restart: always

  db_app:
    image: postgres:12
    container_name: db_app
    environment:
      POSTGRES_DB: settings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - 5434:5432